### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by uncledent** [entria/react-native-view-overflow#1]
FAILURE: Build failed with an exception.

* Where:
Build file '---/node_modules/react-native-view-overflow/android/build.gradle' line: 5

* What went wrong:
A problem occurred evaluating project ':react-native-view-overflow'.
> Could not find method google() for arguments [] on repository container.

the module is linked

**Comment by sibelius** [comment]
add this https://github.com/entria/react-native-view-overflow/blob/master/android/build.gradle#L5

to your project gradle config

**Comment by uncledent** [comment]
My god you are fast :) Thanks, will try it out
