### ISSUE TITLE
Error on build.

### ISSUE THREAD

**Issue by AndreiCalazans** [entria/react-native-view-overflow#2]
### Reproduce:

1. Start a project with react-native init.
2. yarn add react-native-view-overflow
3. react-native link react-native-view-overflow

```
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/Andrei/Documents/lattice/lattice/apps/jakiro/node_modules/react-native-view-overflow/android/build.gradle' line: 5

* What went wrong:
A problem occurred evaluating project ':react-native-view-overflow'.
> Could not find method google() for arguments [] on repository container.
```

It ran well after I downgraded the package to use version 2 of gradle.

**Comment by sibelius** [comment]
please upgrade to gradle 3

we should improve docs to show required steps
