### ISSUE TITLE
Build failes with :Could not find method google() for arguments [] on repository container.

### ISSUE THREAD

**Issue by jascaniojah** [entria/react-native-view-overflow#25]
Im new using RN, after adding this library im facing this at building

**Comment by sibelius** [comment]
add this to your android/build.gradle

```
buildscript {
    repositories {
        jcenter()
        google()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.0'
        classpath 'com.google.gms:google-services:3.1.2'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}
```

maybe we need to add these instructions to docs

**Comment by jascaniojah** [comment]
Still having the same issue.

My android/build.gradle goes like this:

// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
        google()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.3'
        classpath 'com.google.gms:google-services:3.1.2'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        
    }
}

**Comment by sibelius** [comment]
check all the lines you need gradle 3

`classpath 'com.android.tools.build:gradle:3.1.0'`

**Comment by marcojr** [comment]
Still not working for me...Before added google(),  'com.android.tools.build:gradle:3.1.0' on my build.gradle:

* Where:
Build file '/Users/marcojr/Projects/showCase/react_native_js/node_modules/react-native-view-overflow/android/build.gradle' line: 5

* What went wrong:
A problem occurred evaluating project **':react-native-view-overflow'**.
> Could not find method google() for arguments [] on repository container.


Then I added 'com.android.tools.build:gradle:3.1.0' on my build.gradle

Now, I've a different one: 

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/marcojr/Projects/showCase/react_native_js/android/build.gradle' line: 6

* What went wrong:
A problem occurred evaluating root project **'TheSimpsonsRN'**.
> Could not find method google() for arguments [] on repository container.

Where TheSimpsonsRN is the app itself.

**Comment by marcojr** [comment]
What that means, dude ? do you mind to be a little bit specific about your orientation ? what example build.gradle ?

**Comment by sibelius** [comment]
https://github.com/entria/react-native-view-overflow/blob/master/ViewOverflowExample/android/build.gradle#L25

**Comment by maxaggedon** [comment]
Hey @sibelius, would you care to explain why this step is necessary?
I don't have experience developing android apps (apart from react-native) and I have never had to add anything like this to my gradle config when installing native modules.

**Comment by sibelius** [comment]
this is required for gradle 3

**Comment by maxaggedon** [comment]
Ok. But why is it necessary to use gradle 3 then ?
Apart from the fact that I try to understand this complementary config step. I still get the error even after I copy the config from the exemple... It's a shame but I guess it will be quicker for me to tweak my layout in order to make it work than trying to use this package.

**Comment by sibelius** [comment]
all packages are moving to gradle 3 at least

gradle 4 is already available

gradle 2 will be deprecated by Google in the end of this year, so we should upgrade

we use gradle 3 in all our projects, so we'd like to keep consistency

we've provided an example to make this process easier https://github.com/entria/react-native-view-overflow/tree/master/ViewOverflowExample

**Comment by maxaggedon** [comment]
Thanks a lot for the details!

As it now seemed worth investigating a little further, I finally made it work. For those who still have not updated gradle in their react native app, here is what I did:

In **android/gradle/wrapper/gradle-wrapper.properties**:
```diff
-distributionUrl=https\://services.gradle.org/distributions/gradle-2.14.1-all.zip
+distributionUrl=https\://services.gradle.org/distributions/gradle-4.4-all.zip

```

In **android/build.gradle**:
```diff
 buildscript {
     repositories {
         jcenter()
+        google()
     }
     dependencies {
-        classpath 'com.android.tools.build:gradle:2.2.3'
+        classpath 'com.android.tools.build:gradle:3.1.0'
 
         // NOTE: Do not place your application dependencies here; they belong
         // in the individual module build.gradle files

```

And in order ro remove warnings, in **android/app/build.gradle**:
```diff
     compileSdkVersion 23
-    buildToolsVersion "23.0.1"
+    buildToolsVersion "27.0.3"
     defaultConfig {

```

**Comment by sibelius** [comment]
can u send this diff to our docs? it could help a lot of people

**Comment by maxaggedon** [comment]
I would be glad to help sharing this. But I'm not sure whet me exactly by 
> send this diff to our docs
do you want me to send a PR to add it to the docs ? If that's the case, no problem I will do it ;)

Moreover, if I understand well, this is a problem that is going to happen to a lot of people (who bootstrapped their app a while ago) when all packages will require gradle 3+, am I right ?

**Comment by MinaFSedrak** [comment]
still has this issue !!!

**Comment by maxaggedon** [comment]
Ok so I assumed it was working as I was able to build my app, but I just spent the day trying to generate a signed apk for a store release and could not make it work...
There seems to be a lot of people facing problems when upgrading gradle, this issue in the react-native repo is still pretty active:
https://github.com/facebook/react-native/issues/16906

**Comment by gokujy** [comment]
I am getting the same error:
Could not find method google() for arguments [] on repository container
Solve: I'm working on firebase crud and i installed angularfire2 and firebase plugin both.
So i uninstall firebase and error solved, i mean this error coming because conflict.
