### ISSUE TITLE
borderRadius doesn't work for ViewOverflow component  

### ISSUE THREAD

**Issue by GuySerfaty** [entria/react-native-view-overflow#26]
I tried to create an Image inside View with borderRadius: 20 (below) but got without

<img width="531" alt="screen shot 2018-05-29 at 14 58 54" src="https://user-images.githubusercontent.com/17720782/40657929-384a39b8-6352-11e8-9375-0669f263b6cc.png">

**Comment by sibelius** [comment]
check this https://github.com/entria/react-native-view-overflow/issues/10
