### ISSUE TITLE
> Could not find method google() for arguments [] on repository container.

### ISSUE THREAD

**Issue by marcojr** [entria/react-native-view-overflow#30]
I just installed this and now my android app refuses to run...

* Where:
Build file '/Users/marcojr/Projects/showCase/react_native_js/node_modules/react-native-view-overflow/android/build.gradle' line: 5

* What went wrong:
A problem occurred evaluating project ':react-native-view-overflow'.
> Could not find method google() for arguments [] on repository container.

**Comment by sibelius** [comment]
Check example code build.gradle and closed issues

**Comment by ducvu91** [comment]
I check example code build.gradle and  it still error.
