### ISSUE TITLE
Invariant Violation: Native component for "RNViewOverflow" does not exist

### ISSUE THREAD

**Issue by alittletf** [entria/react-native-view-overflow#37]
Hi there, 

I believe I am running into an issue linking the native library. 

I first tried `react-native link react-native-view-overflow` and I got the error in the title. I then went though the manual process and found that each step had already been added to the MainActivity.java, MainApplication.java files, settings.gradle files and build.gradle files. I am a bit stuck. Any thoughts why this isnt working? 

React Native version 0.54.4
React version 16.3.1
react-native-view-overflow version 0.0.3

Thanks,

**Comment by sibelius** [comment]
Check example, your link is wrong

**Comment by Ehsan0007** [comment]
same issue "RNViewOverflow" does not exist

**Comment by sibelius** [comment]
try to run example https://github.com/entria/react-native-view-overflow/tree/master/ViewOverflowExample , if example runs you linking is wrong

**Comment by rafaelsplima** [comment]
same issue "RNViewOverflow" does not exist
