### ISSUE TITLE
Love you man

### ISSUE THREAD

**Issue by yeomann** [entria/react-native-view-overflow#38]
After hours and hours of scratching and everything ok on IOS, here's what worked for me on android
```
<ViewOverflow
    style={{
        zIndex: 100,
        maxHeight: 65,
        overflow: "visible"
    }}
>
```

I couldn't find a way to say you thanks so had to open issue. thank you again! <3 😄

**Comment by sibelius** [comment]
great to hear that

it will probably to fixed sometime in react native core with their new architecture

Best

**Comment by yeomann** [comment]
I think you should edit the core and send this solution as PR no? @sibelius

**Comment by sibelius** [comment]
this https://github.com/entria/react-native-view-overflow/issues/32 needs to be fixed first

if you apply `ViewOverflow` everywhere it makes the app very slow as well

**Comment by yeomann** [comment]
hmmm. I'm currently busy with app development. if possible I will try to look into that issue
