### ISSUE TITLE
cannot build

### ISSUE THREAD

**Issue by menq** [entria/react-native-view-overflow#39]
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/mq/Documents/Lucky/Lucky/node_modules/react-native-view-overflow/android/build.gradle' line: 5

* What went wrong:
A problem occurred evaluating project ':react-native-view-overflow'.
> Could not find method google() for arguments [] on repository container.

**Comment by sibelius** [comment]
Upgrade to gradle 3
