### ISSUE TITLE
Could not find method google() for arguments [] on repository container of type org.gradle.api.internal.artifacts.dsl.DefaultRepositoryHandler.

### ISSUE THREAD

**Issue by ducvu91** [entria/react-native-view-overflow#41]
Hi My Info.
I still Error. Pls help me :(
"dependencies": {
"react": "16.4.1",
"react-native": "0.55.4",
}

"devDependencies": {
    "babel-jest": "23.2.0",
    "babel-preset-react-native": "^2.1.0",
    "jest": "23.3.0",
    "react-test-renderer": "16.4.1",
    "rn-nodeify": "github:tradle/rn-nodeify"
  },

1. android/app/src/main/java/[...]/MainApplication.java

package com.mobisalefcam;

import android.app.Application;

import com.facebook.react.ReactApplication;
import com.entria.views.RNViewOverflowPackage;
import com.reactlibrary.RNSketchViewPackage;
import com.imagepicker.ImagePickerPackage;
import com.oblador.vectoricons.VectorIconsPackage;
import com.learnium.RNDeviceInfo.RNDeviceInfo;
import codes.simen.IMEI.IMEI;
import com.bitgo.randombytes.RandomBytesPackage;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;
import com.facebook.soloader.SoLoader;
import com.airbnb.android.react.maps.MapsPackage;
import com.burnweb.rnpermissions.RNPermissionsPackage;
import com.dieam.reactnativepushnotification.ReactNativePushNotificationPackage;
import org.pgsqlite.SQLitePluginPackage;
import com.terrylinla.rnsketchcanvas.SketchCanvasPackage;

......
return Arrays.<ReactPackage>asList(
          new SQLitePluginPackage(),
          new MainReactPackage(),
          new RNViewOverflowPackage(),
            new RNSketchViewPackage(),
            new ImagePickerPackage(),
            new VectorIconsPackage(),
            new RNDeviceInfo(),
            new IMEI(),
            new RandomBytesPackage(),
            new RNPermissionsPackage(),
            new ReactNativePushNotificationPackage(),
            new MapsPackage(),
            new SketchCanvasPackage()
      );

2. android/settings.gradle:

rootProject.name = 'XXX'

include ':react-native-view-overflow'
project(':react-native-view-overflow').projectDir = new File(rootProject.projectDir, 	'../node_modules/react-native-view-overflow/android')

3. android/app/build.gradle

dependencies {
    compile project(':react-native-view-overflow')
    compile project(':@terrylinla_react-native-sketch-canvas')
    compile project(':react-native-sqlite-storage')
    compile project(':react-native-sketch-draw')
    compile project(':react-native-image-picker')
    compile project(':react-native-vector-icons')
    compile project(':react-native-device-info')
    compile project(':react-native-imei')
    compile project(':react-native-randombytes')
    compile project(':RNPermissionsModule')
    compile project(':react-native-push-notification')
    compile project(':react-native-maps')
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"
    compile "com.facebook.react:react-native:+"  // From node_modules
    compile 'com.google.android.gms:play-services-base:+'
    compile 'com.google.android.gms:play-services-maps:+'

}

4. android/build.gradle

buildscript {
    repositories {
        jcenter()
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.3'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
    }
}

**Comment by sibelius** [comment]
Check example code build.gradle and closed issues
 
Also provide a repository to reproduce this issue
