### ISSUE TITLE
Can't get ViewOverflow to work

### ISSUE THREAD

**Issue by erksch** [entria/react-native-view-overflow#43]
I have a really simple problem: I want an absoluted View to overflow it's parent.
I found this package and was glad that it would solve my problem (since it's not working in android) but I couldn't get it to work.

The following inner View should overflow the outer View (minimal example):

``` javascript
<View style={{ height: 40, backgroundColor: 'gray' }}>
  <View 
    style={{
      width: 100, 
      height: 100, 
      position: 'absolute', 
      backgroundColor: 'blue',
    }} 
  />
</View>
```

I tried every combination of inserting `<ViewOverflow>` or replacing the `<View>` with `<ViewOverflow>` but nothing worked.

Am I doing something wrong or is this a bug?

**Comment by jgcmarins** [comment]
follow this: https://github.com/entria/react-native-view-overflow#react-native-view-overflow

**Comment by sibelius** [comment]
can you post an image of what are you doing?

can you create a repro for this?

**Comment by erksch** [comment]
@sibelius I managed to get it to work after playing around in a demo project. The problem seemed to be that the reloading was not really updating changes made with `<ViewOverflow />` so I had to rebuild most of the time. 

So, this issue can be closed :+1:
