### ISSUE TITLE
Cocoapods installation error

### ISSUE THREAD

**Issue by arielLeverate** [entria/react-native-view-overflow#5]
Hi,

I tried installing via Cocoapods, but get an error over "homepage" in the podspec.

can you update the ios/RNViewOverflow.podspec with the below line of code

`  s.homepage     = "https://github.com/entria/react-native-view-overflow"`

thanks.

**Comment by sibelius** [comment]
we don't use and we don't know much about cocoapods

we gonna accept a PR to fix this

**Comment by sibelius** [comment]
fixed here https://github.com/entria/react-native-view-overflow/pull/6
