### ISSUE TITLE
Add note to README about this library being unnecessary since RN v0.57

### ISSUE THREAD

**Issue by jkdf2** [entria/react-native-view-overflow#57]
Hey, this library really helped us out on React Native v0.54. However, I think you should add a note to the README that React Native supports view overflow for Android for any release covered by this commit: 

https://github.com/facebook/react-native/commit/b81c8b51fc6fe3c2dece72e3fe500e175613c5d4

Which is in RN 0.57 and above :)

**Comment by sibelius** [comment]
is it working without this package?

**Comment by jkdf2** [comment]
Yes. We upgraded from v0.54 to v0.59.10 and changed from ViewOverflow to simple React Native View components, and overflow continues to work.

**Comment by sibelius** [comment]
great, feel free to add a note on README

**Comment by cagils** [comment]
This information is incorrect, as of RN v0.60 overflow: 'visible' is still not supported on Android. The only thing that is supported is showing the item outside the borderRadius but still no element can overflow their container.

**Comment by jkdf2** [comment]
@cagils this is contrary to both my experience and the PR for React Native which I linked. Can you link to an open issue on the React Native GitHub which demonstrates that `overflow: visible` is not supported?

**Comment by jkdf2** [comment]
Oh yeah, I didn't link that this issue is closed by my PR #58
