### ISSUE TITLE
Not working for Flatlist items

### ISSUE THREAD

**Issue by testshallpasswork** [entria/react-native-view-overflow#7]
I have a TabBar component and I'm adding a badge to a tab that is inside a Flatlist. I tried this module out and I'm not getting expected results.

**Code snippet**
```javascript
  <ViewOverflow>
      <FlatList
        style={{overflow: 'visible', marginBottom: 4, zIndex: 5, elevation: 5}}
        contentContainerStyle={{overflow: 'visible'}}
        data={this.state.data}
        keyExtractor={item => item.id}
        extraData={this.state}
        horizontal={true}
        scrollEnabled={false}
        renderItem={({ item, index }) => this.renderItem({ item, index })}
      />
 </ViewOverflow>
```

**Android**
<img width="85" alt="screen shot 2018-04-26 at 4 40 05 pm" src="https://user-images.githubusercontent.com/16087561/39331559-e89fb6d4-4972-11e8-9905-d7b8cf269576.png">

**iOS / expected**
![screen shot 2018-04-26 at 4 54 11 pm](https://user-images.githubusercontent.com/16087561/39331580-f83dd26a-4972-11e8-97e5-64fcdeaa8a46.png)

react-native version: 0.50.4
react-native-view-overflow version: 0.0.3

**Comment by sibelius** [comment]
can you remove `overflow: 'visible'`?

can you try to use `ViewOverflow` in each item?

**Comment by jgfidelis** [comment]
@testshallpasswork, did you find a solution or workaround for this problem?

**Comment by testshallpasswork** [comment]
@jgfidelis I did not yet. I have been distracted with another task. I'm looking to try some other things soon.

**Comment by xiaweiss** [comment]
![image](https://user-images.githubusercontent.com/17960084/39686254-915e2c58-51fa-11e8-9c97-9bbe019a4f62.png)        
I want to use absolute positioning to do the waterfall flow. So I'm going to give ’renderItem’ an absolute position.        
But in fact, the renderItem is wrapped by the View and the CellRenderer, so it doesn't work.

**Comment by xiaweiss** [comment]
@testshallpasswork @jgfidelis  it worked!  you need to use CellRendererComponent and set to ViewOverflow to RenderItem root 

try this:
```
<FlatList
        data={this.state.data}
        keyExtractor={item => item.id}
        CellRendererComponent={ViewOverflow}  
        renderItem={({ item, index }) => (
<ViewOverflow style={{position: 'absolute', left: 100, top: 100}}>
   // item....
</ViewOverflow>
)}
/>
```

**Comment by xiaweiss** [comment]
>It's worth noting that `CellRendererComponent={ViewOverflow}` was introduced in react-native 0.52. I also still had no luck in my use case. 

@testshallpasswork please checked your code. renderItem also need ViewOverflow. The resaon you can see issue #14

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by testshallpasswork** [comment]
@xiaweiss I had that but the problem I faced was the Flatlist is horizontal and it would not overflow/overlap components outside the context of the Flatlist. I was able to address by adding the outside component (in my case a top navigation bar) that was above the Flatlist and render it as the header. After doing so, it would overlap correctly. I'm not sure if this was best solution but it's what finally worked.

**Comment by pixelize** [comment]
@testshallpasswork @xiaweiss @sibelius is seems not working anymore, in addition CellRendererComponent props is no more supported on `FlatList`

**Comment by xiaweiss** [comment]
@pixelize Try to use the latest version of React Native ?  
The Newer version fixed this problem with same way, so you do not need react-native-view-overflow now.

**Comment by pixelize** [comment]
@xiaweiss i'm using RN 0.59.10 

```jsx
<FlatList
      contentContainerStyle={{ overflow: "visible" }}
      horizontal
      data={[{key: 'a'}, {key: 'b'}]}
      renderItem={({item}) => <View style={{ elevation: 4, backgroundColor: "red", padding: 10}}><Text>{item.key}</Text></View>}
    />
```

but still can't view shadow from elevation :(

**Comment by xiaweiss** [comment]
Emmm..... Maybe shadow problem in Android, elevation can not work good both in Android and  iOS


发自我的iPhone

------------------ Original ------------------

**Comment by xiaweiss** [comment]
I used react-native-shadow-view,  it dependence react-native-svg

**Comment by pixelize** [comment]
@xiaweiss i'm gonna have a try with `react-native-shadow-view`, thank you very much for helping !

**Comment by FRizzonelli** [comment]
@pixelize Any news? I'm tilting so hard. I'm just trying to do a simple flatlist with 3 items and elevation. Shadow is truncated by padding of the list. This makes no sense...

**Comment by pixelize** [comment]
@FRizzonelli Same here, cannot make it... The only super ugly solution I found is to put extra margin on items so the elevation can be shown :( If you found another proper way, i'm all ears :P

**Comment by FRizzonelli** [comment]
Same solution I've found, but you cannot use list separator :( Really cringe to me 😭

**Comment by pixelize** [comment]
Yup, If i find something better, I will let you know for sure :/ 

Here is my test example 👍 

```jsx
const styles = StyleSheet.create({
  card: {
    backgroundColor: "tomato",
    borderRadius: 8,
    elevation: 8,
    padding: 10,
    marginRight: 10,
  },
});

const MainApp = props => (
  <View style={{ margin: 30}}>
    <FlatList
      horizontal
      data={[
        { text: "Lorem ipsum dolor." },
        { text: "Lorem ipsum dolor." },
        { text: "Lorem ipsum dolor." },
        { text: "Lorem ipsum dolor." },
        { text: "Lorem ipsum dolor." },
        { text: "Lorem ipsum dolor." },
      ]}
      renderItem={({ item }) => (
        <View style={styles.card}>
          <Text>{item.text}</Text>
        </View>
      )}
    />
  </View>
);
```
