### ISSUE TITLE
cannot find symbol for android

### ISSUE THREAD

**Issue by CmerCy132** [entria/react-native-view-overflow#8]
Error : 

error: cannot find symbol
import com.reactlibrary.RNViewOverflowPackage;

symbol:   class RNViewOverflowPackage
location: package com.reactlibrary

error: cannot find symbol
                    new RNViewOverflowPackage()

symbol: class RNViewOverflowPackage

build.gradle: 

    buildscript {
        repositories {
            jcenter()
            maven { url 'https://maven.google.com' }
        }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.0'
        // classpath 'com.android.tools.build:gradle:2.3.3'
        }
    }

    apply plugin: 'com.android.library'

    def DEFAULT_COMPILE_SDK_VERSION = 26
    def DEFAULT_BUILD_TOOLS_VERSION = "27.0.3"
    def DEFAULT_TARGET_SDK_VERSION = 26

    android {
        compileSdkVersion rootProject.hasProperty('compileSdkVersion') ? rootProject.compileSdkVersion : DEFAULT_COMPILE_SDK_VERSION
        buildToolsVersion rootProject.hasProperty('buildToolsVersion') ? rootProject.buildToolsVersion : DEFAULT_BUILD_TOOLS_VERSION

    defaultConfig {
            minSdkVersion 16
            targetSdkVersion rootProject.hasProperty('targetSdkVersion') ? rootProject.targetSdkVersion :     DEFAULT_TARGET_SDK_VERSION
            versionCode 1
            versionName "1.0"
        }
    lintOptions {
            abortOnError false
        }
    }

    repositories {
        mavenCentral()
    // google()
        maven {
            url 'https://maven.google.com/'
            name 'Google'
            }
        }

    dependencies {
    compile 'com.facebook.react:react-native:+'
    }

**Comment by sibelius** [comment]
your link is wrong

**Comment by CmerCy132** [comment]
What link to I need to use?
